### ISSUE TITLE
does not currently work on edge

### ISSUE THREAD

**Issue by anunusedusernamesoitismoredifficult4all** [BenMcAvoy/Spark#1]
1. chrome://extensions redirects you to **edge://extensions/** on edge automatically
2. The file doesn't save on edge (on the downloads drop down it deletes it instead of opening the file location)

 ![image](https://github.com/BenMcAvoy/Spark/assets/152713145/b8dab30d-9d53-4983-ac97-0ff893a3b498)

4. You can't drag the file (if you find it) into edge (with: edge://extensions/) and chrome web extensions (for edge)

![image](https://github.com/BenMcAvoy/Spark/assets/152713145/d8f95103-0b34-485c-b47d-642527cf03c6)

5. while using edge and going to **https://chromewebstore.google.com/category/extensions?hl** you can't enable developer mode
6. Package is invalid

![image](https://github.com/BenMcAvoy/Spark/assets/152713145/532c7ac1-9ab8-4a63-a069-e8dbbe6026fb)

**- On windows 11 -**

**Comment by BenMcAvoy** [comment]
I am aware of the redirect, this is due to the chromium base. 
You need to press "Keep" on the crx file
The developer mode toggle is in the sidebar on edge://extensions

Hope this helps

**Comment by BenMcAvoy** [comment]
Unfortunately I cannot demo this is I have already allowed it in my instance of edge.

In this image here
![image](https://github.com/BenMcAvoy/Spark/assets/143108602/e12371ec-1b24-420d-837c-5d4d110e667b)
Next to the file should be 3 dots, if you click the three dots, there should be a keep button.

You can see my developer mode toggle on the left hand side here
![image](https://github.com/BenMcAvoy/Spark/assets/143108602/fb462319-4771-41c8-addc-971b8afd1964)
It may be hidden in a hamburger menu next to the "Extensions" title if your window is not fullscreen.

**Comment by BenMcAvoy** [comment]
You should then be able to use Load unpacked and the browser should no longer care about the invalid certificates. I would have to pay to add this to a store and get the certificates which is not part of the current plan.

**Comment by anunusedusernamesoitismoredifficult4all** [comment]
I Believe you want me to:

1. Download https://github.com/BenMcAvoy/Spark/releases/download/0.0.1/Spark.crx
2. "save" or "save as"
![image](https://github.com/BenMcAvoy/Spark/assets/152713145/35d4e13c-3d64-4d51-b2d8-ad037b21115d)
3. Open file location
![image](https://github.com/BenMcAvoy/Spark/assets/152713145/c3fc94e1-faaa-44d5-bb5c-ffdd17b70084)
4. It gets deleted
![image](https://github.com/BenMcAvoy/Spark/assets/152713145/1bb11682-b42e-4d7c-aece-8a0b14f5ac9b)
5. I notice pcakage is invalid at the top of edge
![image](https://github.com/BenMcAvoy/Spark/assets/152713145/2e3cfbf8-46df-48f1-a18b-4e7eaf70328e)

**Comment by anunusedusernamesoitismoredifficult4all** [comment]
I cannot get the file to the point where I can drag or drop into **edge://extensions**

**Comment by BenMcAvoy** [comment]
I see in one of your screenshots it looks like the file is downloaded to your system. Is this correct? Is the file on the actual system?

**Comment by anunusedusernamesoitismoredifficult4all** [comment]
Only in the recent tab:

![image](https://github.com/BenMcAvoy/Spark/assets/152713145/f391a57a-b11b-4d25-87e4-dfacec0d7cdd)

I believe this is the screenshot you are talking about

**Comment by BenMcAvoy** [comment]
Yes, you *should* be able to drag and drop that file into the `edge://extensions` page as long as you have developer mode on

**Comment by anunusedusernamesoitismoredifficult4all** [comment]
While developer mode is on: 
![image](https://github.com/BenMcAvoy/Spark/assets/152713145/7e7169f6-7b93-4f3b-aefa-516ee8afbda7)

1. I drag the file as a box with a file icon appears with the words "copy" under appears.
2. Nothing happens after I release the left mouse button.

**Comment by BenMcAvoy** [comment]
This extension is in a packed form. It sounds odd, now that I am adding it to edge, I get this
![image](https://github.com/BenMcAvoy/Spark/assets/143108602/123cd6f5-ec43-4966-bb84-b6eceb72518f)

**Comment by BenMcAvoy** [comment]
![image](https://github.com/BenMcAvoy/Spark/assets/143108602/8937b093-a324-45c1-996a-cc68d3513a37)
You will also have to tick "Allow extensions from other stores"

Personally, I get this error despite not having before, just got it now after reinstalling the extension.

I would recommend using a different browser for now that is also Chromium based whilst this is worked on

**Comment by BenMcAvoy** [comment]
I may end up switching to loading unpacked extensions as this seems like the [official documentation](https://support.google.com/chrome_webstore/answer/2811969?hl=en) for the solution:
> If you need to use a disabled extension, you can contact the extension’s developer and ask them to upload their extension to the Chrome Web Store. This will allow you, and other people who use Chrome, to install that extension from the Chrome Web Store, or if you already have it installed, to manually re-enable it from your list of extensions.

This is something I cannot do in my current situation and I will have to explore other solutions.

**Comment by anunusedusernamesoitismoredifficult4all** [comment]
> ![image](https://private-user-images.githubusercontent.com/143108602/287465206-8937b093-a324-45c1-996a-cc68d3513a37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1Mzk4MDcsIm5iZiI6MTcwMTUzOTUwNywicGF0aCI6Ii8xNDMxMDg2MDIvMjg3NDY1MjA2LTg5MzdiMDkzLWEzMjQtNDVjMS05OTZhLWNjNjhkMzUxM2EzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMlQxNzUxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOGFhZDUyMTkzY2IzNDYwMjg1YjI4NTJiOTE4YWQyOTYwYTg2NTZjZmMxMjYxZWY4MmY3ODIzMTY4NTFkYjQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.35CxHnClixnXPqe7RD5k2i9rwNt7NMCnbLXpOSFQC8U) You will also have to tick "Allow extensions from other stores"
I was already allowing extensions form other stores
Which is why I asked where the enable developer button is for chrome web extensions:
https://chrome.google.com/webstore/category/extensions?hl=en-GB

**Comment by BenMcAvoy** [comment]
It seems there is nothing I can do according to the official documentation, sorry.
